return {}
-- return {
--   {
--     "sourcegraph/sg.nvim",
--     dependencies = { "nvim-lua/plenary.nvim", "nvim-telescope/telescope.nvim" },
--     config = function()
--       local sg = require("sg")
--       sg.setup({})
-- 
--       vim.keymap.set("n", "<leader>m", sg.search, { desc = "SourceGraph search" })
--     end
--   },
-- }
